// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpnpbhcccjvcdbrtboqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwbnBiaGNjY2p2Y2RicnRib3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzUyOTUsImV4cCI6MjA2NTQ1MTI5NX0.xH7iAW5HVLdDKeEyDemchq5QXvJSjvoCh18_aN-qv14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);